# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Comments',
        ),
    ]
